server:
  port: 8084
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://127.0.0.1:8080/eureka
      register-with-eureka: true
      fetch-registry: true
    instance:
      lease-renewal-interval-in-seconds: 3
      lease-expiration-duration-in-seconds: 5
management:
  endpoints:
    web:
      exposure:
        include: "*"
