spring: 
  eureka: 
    client: 
      service-url: 
      defaultZone: http://127.0.0.1:8080/eureka 
      fetch-registry: true 
      register-with-eureka: true 
server: 
  port: 8082 
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*"
